name: Example workflow

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  checkLabels:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.labels.*.name[0]}}
    steps:
      - run: echo Check labels is not empty.
      - run: echo contains( toJson(github), 'stop_ci' )
      - run: echo contains(github.event.pull_request.labels.*.name, 'stop_ci')
  checkLabel_ci:
    runs-on: ubuntu-latest
    if: contains( toJson(github), 'stop_ci' )
    steps:
      - run: echo Check labels is stop_ci
  checkLabel_ci2:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'stop_ci')
    steps:
      - run: echo Check labels is stop_ci
  build:
    needs: [checkLabels]
    strategy:
      matrix:
        label: ${{github.event.pull_request.labels.*.name}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world from "${{matrix.label}}"!
